config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  post '' => 'posts#create'
  resources :posts, :except => [:index, :new, :create, :destroy, :edit, :update]
  resources :post_comments, :only => [:create, :destroy]

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'registration' }

  namespace :admin do
    resources :posts, :only => [:new, :create, :destroy, :edit, :update]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  validates :title, presence: true
  has_many :comments, class_name: "PostComment"
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /admin/posts/new
  def new
    @post = Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      if @post.errors.any?
        flash[:error] = @post.errors.full_messages
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      if @post.errors.any?
        flash[:error] = @post.errors.full_messages
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :announcement, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :announcement, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def posts_path
        root_path
    end
end

app/views/posts/index.html.erb
<% title 'Свежие публикации' %>
<h1>Свежие публикации</h1>
<%= flash_messages %>
<% if @posts.any? %>
<% @posts.each do |post| %>
    <div class="post">
      <h2 class="post-title"><%= link_to post.title, post %></h2>

      <div class="text-muted post-info">
        <span>Дата публикации: <%= l post.created_at.to_date %></span>
        <span>Кол-во комментариев: <%= post.comments.count %></span>
      </div>
      <div class="post-announcement">
        <%= markdown post.announcement %>
      </div>
    </div>
    <hr>
<% end %>

<% else %>
<p class="none">Нет постов</p>
<% end %>

app/views/posts/show.html.erb
<% title @post.title %>
<% breadcrumb :post, @post %>
<div class="post">
  <h2><%= @post.title %></h2>

  <div class="text-muted post-info">
    <span>Дата публикации: <%= l @post.created_at.to_date %></span>
    <span>Кол-во комментариев: <%= @post.comments.count %></span></span>
  </div>

  <div class="post-content">
    <%= markdown @post.content %>
  </div>
</div>
<% if can? :update, @post %>
    <%= link_to 'Редактировать', edit_admin_post_path(@post), class: "btn btn-success" %>
<% end %>
<hr>
<h3>Комментарии</h3>
<%= flash_messages %>
<%= form_for(@post.comments.new) do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <div class="form-group">
      <%= f.text_area :content, class: "form-control", rows: 5 %>
    </div>
    <%= f.submit "Отправить", class: "btn btn-default" %>
<% end %>
<% if @post.comments.all.empty? %>
    <p class="none">Нет комментариев</p>
<% else %>
    <% @post.comments.all.each do |comment| %>
        <hr>
        <div class="row">
          <div class="col-sm-2">
            <img src="<%= avatar_url comment.user %>?s=300" class="img-thumbnail img-responsive">
          </div>
          <div class="col-sm-10">
            <h3><%= comment.user.email %></h3>
            <p class="text-muted"><%= l comment.created_at.to_date %></p>
            <%= comment.content %>
            <% if can? :destroy, comment %>
                <%= link_to comment,  method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger"  do %>
                    <i class="glyphicon glyphicon-trash"></i> Удалить
                <% end %>
            <% end %>
          </div>
        </div>
    <% end %>
<% end %>